<a href="https://colab.research.google.com/github/fahadrajput99/EDA-Using-Pandas/blob/main/black_friday.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
%matplotlib inline

In [2]:
df_test=pd.read_csv('/content/test.csv')
df_test.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3
0,1000004,P00128942,M,46-50,7,B,2,1,1,11.0,NaN
1,1000009,P00113442,M,26-35,17,C,0,0,3,5.0,NaN
2,1000010,P00288442,F,36-45,1,B,4+,1,5,14.0,NaN
3,1000010,P00145342,F,36-45,1,B,4+,1,4,9.0,NaN
4,1000011,P00053842,F,26-35,1,C,1,0,4,5.0,12.0

In [3]:
df_train=pd.read_csv('/content/train.csv')
df_train

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969
...,...,...,...,...,...,...,...,...,...,...,...,...
550063,1006033,P00372445,M,51-55,13,B,1,1,20,NaN,NaN,368
550064,1006035,P00375436,F,26-35,1,C,3,0,20,NaN,NaN,371
550065,1006036,P00375436,F,26-35,15,B,4+,1,20,NaN,NaN,137
550066,1006038,P00375436,F,55+,1,C,2,0,20,NaN,NaN,365
550067,1006039,P00371644,F,46-50,0,B,4+,1,20,NaN,NaN,490

In [4]:
df=df_test.append(df_train)
df

<ipython-input-4-ef1839f14e8f>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df_test.append(df_train)

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000004,P00128942,M,46-50,7,B,2,1,1,11.0,NaN,NaN
1,1000009,P00113442,M,26-35,17,C,0,0,3,5.0,NaN,NaN
2,1000010,P00288442,F,36-45,1,B,4+,1,5,14.0,NaN,NaN
3,1000010,P00145342,F,36-45,1,B,4+,1,4,9.0,NaN,NaN
4,1000011,P00053842,F,26-35,1,C,1,0,4,5.0,12.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
550063,1006033,P00372445,M,51-55,13,B,1,1,20,NaN,NaN,368.0
550064,1006035,P00375436,F,26-35,1,C,3,0,20,NaN,NaN,371.0
550065,1006036,P00375436,F,26-35,15,B,4+,1,20,NaN,NaN,137.0
550066,1006038,P00375436,F,55+,1,C,2,0,20,NaN,NaN,365.0
550067,1006039,P00371644,F,46-50,0,B,4+,1,20,NaN,NaN,490.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 783667 entries, 0 to 550067
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   User_ID                     783667 non-null  int64
 1   Product_ID                  783667 non-null  object
 2   Gender                      783667 non-null  object
 3   Age                         783667 non-null  object
 4   Occupation                  783667 non-null  int64
 5   City_Category               783667 non-null  object
 6   Stay_In_Current_City_Years  783667 non-null  object
 7   Marital_Status              783667 non-null  int64
 8   Product_Category_1          783667 non-null  int64
 9   Product_Category_2          537685 non-null  float64
 10  Product_Category_3          237858 non-null  float64
 11  Purchase                    550068 non-null  float64
dtypes: float64(3), int64(4), object(5)
memory usage: 77.7+ MB

In [6]:
df.drop(['User_ID'],axis=1)

,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,P00128942,M,46-50,7,B,2,1,1,11.0,NaN,NaN
1,P00113442,M,26-35,17,C,0,0,3,5.0,NaN,NaN
2,P00288442,F,36-45,1,B,4+,1,5,14.0,NaN,NaN
3,P00145342,F,36-45,1,B,4+,1,4,9.0,NaN,NaN
4,P00053842,F,26-35,1,C,1,0,4,5.0,12.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
550063,P00372445,M,51-55,13,B,1,1,20,NaN,NaN,368.0
550064,P00375436,F,26-35,1,C,3,0,20,NaN,NaN,371.0
550065,P00375436,F,26-35,15,B,4+,1,20,NaN,NaN,137.0
550066,P00375436,F,55+,1,C,2,0,20,NaN,NaN,365.0
550067,P00371644,F,46-50,0,B,4+,1,20,NaN,NaN,490.0

In [7]:
df.describe()

,User_ID,Occupation,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
count,7.836670e+05,783667.000000,783667.000000,783667.000000,537685.000000,237858.000000,550068.000000
mean,1.003029e+06,8.079300,0.409777,5.366196,9.844506,12.668605,9263.968713
std,1.727267e+03,6.522206,0.491793,3.878160,5.089093,4.125510,5023.065394
min,1.000001e+06,0.000000,0.000000,1.000000,2.000000,3.000000,12.000000
25%,1.001519e+06,2.000000,0.000000,1.000000,5.000000,9.000000,5823.000000
50%,1.003075e+06,7.000000,0.000000,5.000000,9.000000,14.000000,8047.000000
75%,1.004478e+06,14.000000,1.000000,8.000000,15.000000,16.000000,12054.000000
max,1.006040e+06,20.000000,1.000000,20.000000,18.000000,18.000000,23961.000000

In [8]:
df.isnull().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            245982
Product_Category_3            545809
Purchase                      233599
dtype: int64

In [15]:
df = pd.get_dummies(df, columns=['Gender'])

KeyError: "None of [Index(['Gender'], dtype='object')] are in the [columns]"

In [13]:
df

,User_ID,Product_ID,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Gender_F,Gender_M
0,1000004,P00128942,46-50,7,B,2,1,1,11.0,NaN,NaN,0,1
1,1000009,P00113442,26-35,17,C,0,0,3,5.0,NaN,NaN,0,1
2,1000010,P00288442,36-45,1,B,4+,1,5,14.0,NaN,NaN,1,0
3,1000010,P00145342,36-45,1,B,4+,1,4,9.0,NaN,NaN,1,0
4,1000011,P00053842,26-35,1,C,1,0,4,5.0,12.0,NaN,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
550063,1006033,P00372445,51-55,13,B,1,1,20,NaN,NaN,368.0,0,1
550064,1006035,P00375436,26-35,1,C,3,0,20,NaN,NaN,371.0,1,0
550065,1006036,P00375436,26-35,15,B,4+,1,20,NaN,NaN,137.0,1,0
550066,1006038,P00375436,55+,1,C,2,0,20,NaN,NaN,365.0,1,0
550067,1006039,P00371644,46-50,0,B,4+,1,20,NaN,NaN,490.0,1,0

In [14]:
df.isnull().sum()

User_ID                            0
Product_ID                         0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            245982
Product_Category_3            545809
Purchase                      233599
Gender_F                           0
Gender_M                           0
dtype: int64

In [17]:
df.dtypes

User_ID                         int64
Product_ID                     object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
Purchase                      float64
Gender_F                        uint8
Gender_M                        uint8
dtype: object

In [18]:
df.drop(['User_ID'],axis=1,inplace=True)

In [19]:
df['Age'].unique()

array(['46-50', '26-35', '36-45', '18-25', '51-55', '55+', '0-17'],
      dtype=object)

In [20]:
df['Age']=df['Age'].map({'0-17':1,'18-25':2,'26-35':3,'36-45':4,'46-50':5,'51-55':6,'55+':7})

In [21]:

# Import label encoder
from sklearn import preprocessing

# label_encoder object knows
# how to understand word labels.
label_encoder = preprocessing.LabelEncoder()

# Encode labels in column 'species'.
df['Age']= label_encoder.fit_transform(df['Age'])

df['Age'].unique()

array([4, 2, 3, 1, 5, 6, 0])

In [22]:
df

,Product_ID,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Gender_F,Gender_M
0,P00128942,4,7,B,2,1,1,11.0,NaN,NaN,0,1
1,P00113442,2,17,C,0,0,3,5.0,NaN,NaN,0,1
2,P00288442,3,1,B,4+,1,5,14.0,NaN,NaN,1,0
3,P00145342,3,1,B,4+,1,4,9.0,NaN,NaN,1,0
4,P00053842,2,1,C,1,0,4,5.0,12.0,NaN,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
550063,P00372445,5,13,B,1,1,20,NaN,NaN,368.0,0,1
550064,P00375436,2,1,C,3,0,20,NaN,NaN,371.0,1,0
550065,P00375436,2,15,B,4+,1,20,NaN,NaN,137.0,1,0
550066,P00375436,6,1,C,2,0,20,NaN,NaN,365.0,1,0
550067,P00371644,4,0,B,4+,1,20,NaN,NaN,490.0,1,0

In [23]:
df_city=pd.get_dummies(df['City_Category'],drop_first=True)

In [24]:
df_city

        B  C
0       1  0
1       0  1
2       1  0
3       1  0
4       0  1
...    .. ..
550063  1  0
550064  0  1
550065  1  0
550066  0  1
550067  1  0

[783667 rows x 2 columns]

In [25]:
df=pd.concat([df,df_city],axis=1)

In [26]:
df

,Product_ID,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Gender_F,Gender_M,B,C
0,P00128942,4,7,B,2,1,1,11.0,NaN,NaN,0,1,1,0
1,P00113442,2,17,C,0,0,3,5.0,NaN,NaN,0,1,0,1
2,P00288442,3,1,B,4+,1,5,14.0,NaN,NaN,1,0,1,0
3,P00145342,3,1,B,4+,1,4,9.0,NaN,NaN,1,0,1,0
4,P00053842,2,1,C,1,0,4,5.0,12.0,NaN,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550063,P00372445,5,13,B,1,1,20,NaN,NaN,368.0,0,1,1,0
550064,P00375436,2,1,C,3,0,20,NaN,NaN,371.0,1,0,0,1
550065,P00375436,2,15,B,4+,1,20,NaN,NaN,137.0,1,0,1,0
550066,P00375436,6,1,C,2,0,20,NaN,NaN,365.0,1,0,0,1
550067,P00371644,4,0,B,4+,1,20,NaN,NaN,490.0,1,0,1,0

In [27]:
df.drop(['City_Category'],axis=1,inplace=True)

In [28]:
df

,Product_ID,Age,Occupation,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Gender_F,Gender_M,B,C
0,P00128942,4,7,2,1,1,11.0,NaN,NaN,0,1,1,0
1,P00113442,2,17,0,0,3,5.0,NaN,NaN,0,1,0,1
2,P00288442,3,1,4+,1,5,14.0,NaN,NaN,1,0,1,0
3,P00145342,3,1,4+,1,4,9.0,NaN,NaN,1,0,1,0
4,P00053842,2,1,1,0,4,5.0,12.0,NaN,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
550063,P00372445,5,13,1,1,20,NaN,NaN,368.0,0,1,1,0
550064,P00375436,2,1,3,0,20,NaN,NaN,371.0,1,0,0,1
550065,P00375436,2,15,4+,1,20,NaN,NaN,137.0,1,0,1,0
550066,P00375436,6,1,2,0,20,NaN,NaN,365.0,1,0,0,1
550067,P00371644,4,0,4+,1,20,NaN,NaN,490.0,1,0,1,0

In [29]:
df.isnull().sum()

Product_ID                         0
Age                                0
Occupation                         0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            245982
Product_Category_3            545809
Purchase                      233599
Gender_F                           0
Gender_M                           0
B                                  0
C                                  0
dtype: int64

In [30]:
df['Product_Category_2'] = df['Product_Category_2'].fillna(df['Product_Category_2'].mode().iloc[0])
df

,Product_ID,Age,Occupation,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Gender_F,Gender_M,B,C
0,P00128942,4,7,2,1,1,11.0,NaN,NaN,0,1,1,0
1,P00113442,2,17,0,0,3,5.0,NaN,NaN,0,1,0,1
2,P00288442,3,1,4+,1,5,14.0,NaN,NaN,1,0,1,0
3,P00145342,3,1,4+,1,4,9.0,NaN,NaN,1,0,1,0
4,P00053842,2,1,1,0,4,5.0,12.0,NaN,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
550063,P00372445,5,13,1,1,20,8.0,NaN,368.0,0,1,1,0
550064,P00375436,2,1,3,0,20,8.0,NaN,371.0,1,0,0,1
550065,P00375436,2,15,4+,1,20,8.0,NaN,137.0,1,0,1,0
550066,P00375436,6,1,2,0,20,8.0,NaN,365.0,1,0,0,1
550067,P00371644,4,0,4+,1,20,8.0,NaN,490.0,1,0,1,0

In [31]:
df['Product_Category_3'] = df['Product_Category_3'].fillna(df['Product_Category_3'].mode().iloc[0])
df

,Product_ID,Age,Occupation,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Gender_F,Gender_M,B,C
0,P00128942,4,7,2,1,1,11.0,16.0,NaN,0,1,1,0
1,P00113442,2,17,0,0,3,5.0,16.0,NaN,0,1,0,1
2,P00288442,3,1,4+,1,5,14.0,16.0,NaN,1,0,1,0
3,P00145342,3,1,4+,1,4,9.0,16.0,NaN,1,0,1,0
4,P00053842,2,1,1,0,4,5.0,12.0,NaN,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
550063,P00372445,5,13,1,1,20,8.0,16.0,368.0,0,1,1,0
550064,P00375436,2,1,3,0,20,8.0,16.0,371.0,1,0,0,1
550065,P00375436,2,15,4+,1,20,8.0,16.0,137.0,1,0,1,0
550066,P00375436,6,1,2,0,20,8.0,16.0,365.0,1,0,0,1
550067,P00371644,4,0,4+,1,20,8.0,16.0,490.0,1,0,1,0

In [32]:
df.isnull().sum()

Product_ID                         0
Age                                0
Occupation                         0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2                 0
Product_Category_3                 0
Purchase                      233599
Gender_F                           0
Gender_M                           0
B                                  0
C                                  0
dtype: int64

In [41]:
df.dtypes

Product_ID                     object
Age                             int64
Occupation                      int64
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
Purchase                      float64
Gender_F                        uint8
Gender_M                        uint8
B                               uint8
C                               uint8
dtype: object

In [42]:
df['Stay_In_Current_City_Years'] = df['Stay_In_Current_City_Years'].replace('4+', '4')

In [43]:
df

,Product_ID,Age,Occupation,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase,Gender_F,Gender_M,B,C
0,P00128942,4,7,2,1,1,11.0,16.0,NaN,0,1,1,0
1,P00113442,2,17,0,0,3,5.0,16.0,NaN,0,1,0,1
2,P00288442,3,1,4,1,5,14.0,16.0,NaN,1,0,1,0
3,P00145342,3,1,4,1,4,9.0,16.0,NaN,1,0,1,0
4,P00053842,2,1,1,0,4,5.0,12.0,NaN,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
550063,P00372445,5,13,1,1,20,8.0,16.0,368.0,0,1,1,0
550064,P00375436,2,1,3,0,20,8.0,16.0,371.0,1,0,0,1
550065,P00375436,2,15,4,1,20,8.0,16.0,137.0,1,0,1,0
550066,P00375436,6,1,2,0,20,8.0,16.0,365.0,1,0,0,1
550067,P00371644,4,0,4,1,20,8.0,16.0,490.0,1,0,1,0

In [44]:
df['Stay_In_Current_City_Years'] = df['Stay_In_Current_City_Years'].astype(int)

In [47]:
df.dtypes

Product_ID                     object
Age                             int64
Occupation                      int64
Stay_In_Current_City_Years      int64
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
Purchase                      float64
Gender_F                        int64
Gender_M                        int64
B                               int64
C                               int64
dtype: object

In [46]:
df['Gender_F']=df['Gender_F'].astype(int)
df['Gender_M']=df['Gender_M'].astype(int)
df['B']=df['B'].astype(int)
df['C']=df['C'].astype(int)